// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: classes/grpc/Student.proto

package com.netty.demo.demo12.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.demo.grpc.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
