// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: classes/grpc/Student.proto

package com.netty.demo.demo12.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.demo.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
