// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.demo.demo12.grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_MyRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_MyResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_StudentRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_StudentResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_StudentResponseList_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_StreamRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_grpc_StreamResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\023com.netty.demo.grpc\"\035\n\t" +
      "MyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRespons" +
      "e\022\020\n\010realname\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n" +
      "\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 " +
      "\001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"T\n\023Studen" +
      "tResponseList\022=\n\017studentResponse\030\001 \003(\0132$" +
      ".com.netty.demo.grpc.StudentResponse\"%\n\r" +
      "StreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016S" +
      "treamResponse\022\025\n\rresponse_info\030\001 \001(\t2\215\003\n" +
      "\016StudentService\022X\n\025GetRealNameByUsername" +
      "\022\036.com.netty.demo.grpc.MyRequest\032\037.com.n" +
      "etty.demo.grpc.MyResponse\022^\n\017GetStudentB" +
      "yAge\022#.com.netty.demo.grpc.StudentReques" +
      "t\032$.com.netty.demo.grpc.StudentResponse0" +
      "\001\022j\n\027GetStudentWrapperByAges\022#.com.netty" +
      ".demo.grpc.StudentRequest\032(.com.netty.de" +
      "mo.grpc.StudentResponseList(\001\022U\n\006BiTask\022" +
      "\".com.netty.demo.grpc.StreamRequest\032#.co" +
      "m.netty.demo.grpc.StreamResponse(\0010\001B,\n\032" +
      "com.netty.demo.demo12.grpcB\014StudentProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netty_demo_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_demo_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_netty_demo_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netty_demo_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_netty_demo_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_netty_demo_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_netty_demo_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_netty_demo_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_netty_demo_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_netty_demo_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_netty_demo_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_netty_demo_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_com_netty_demo_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_netty_demo_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_grpc_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
